/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @next/next/no-img-element */
import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";






const CreatePostWizard = () =>{
  const {user} = useUser();
  console.log(user);
  if(!user) return null;
  return (
    <div className="flex gap-4 w-full">
    <img className = "w-12   border-b-2 rounded-full h-12"  src= {user.imageUrl} alt="user pic"/>
    <input
    className=" bg-transparent p-4 grow outline-none"
    placeholder="whats on your mind..." 
    type="text"/>
    </div>
  )
  
}

export default function Home() {
  
  const user = useUser();

  const {data,isLoading} = api.posts.getAll.useQuery();

 if(!data) return <div>Something Went Wrong...</div>
 if(isLoading) return <div>Loading...</div>



  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full border-slate-900 h-screen md:max-w-2xl bg-white border-x">

        
        <div className="text-black border-b p-4  border-slate-900">
          {!user.isSignedIn && <SignInButton/>}
          {!!user.isSignedIn && <CreatePostWizard/>}
        </div>
        <div>
          {data?.map((post,author)=>(
            <div className="p-8 border-b-2 border-slate-800" key={post.id}>{post.content}
            <p>{author}</p>
            </div>
          ))}
        </div>
        </div>
      </main>
    </>
  );
}
